version = 0.1

[default.global.parameters]
stack_name = "amm-purchase-aproval"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "amm-purchase-aproval"
profile = "amm-dev"
parameter_overrides = "StageName=\"prod\" AllowedOrigin=\"http://localhost:3000\" ApproverAppUrl=\"http://localhost:3000\""
image_repositories = []

[default.local_start_api.parameters]
warm_containers = "EAGER"
